# Imports

In [1]:
import sys
sys.path.append('../../')

from Understat.Understat import UnderstatScrapper

# Scrapper

In [2]:
scrapper = UnderstatScrapper()

# Match

## Single Match

In [3]:
dfs, home_team, away_team = scrapper.scrape_match("https://understat.com/match/26967")

/home/victor/Documentos/Programação/Football/Scrapping/experiments/OwnScrapper/../../Understat/Understat.py:64: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 64 of the file /home/victor/Documentos/Programação/Football/Scrapping/experiments/OwnScrapper/../../Understat/Understat.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(res.content)

In [4]:
home_team, away_team

('Crystal Palace', 'Wolverhampton Wanderers')

In [5]:
dfs[1].head()

,id,goals,own_goals,shots,xG,time,player_id,team_id,position,player,...,yellow_card,red_card,roster_in,roster_out,key_passes,assists,xA,xGChain,xGBuildup,positionOrder
0,729279,0,0,0,0,90,7702,78,GK,Dean Henderson,...,0,0,0,0,0,0,0,0,0,1
1,729282,0,0,0,0,74,510,78,DC,Joel Ward,...,1,0,729292,0,1,0,0.06846939772367477,0.10464299470186234,0.10464299470186234,3
2,729280,0,0,0,0,90,8853,78,DC,Maxence Lacroix,...,0,0,0,0,0,0,0,0.16315193474292755,0.16315193474292755,3
3,729281,0,0,0,0,90,8430,78,DC,Chris Richards,...,0,0,0,0,0,0,0,0.21019722521305084,0.21019722521305084,3
4,729283,0,0,1,0.12534911930561066,90,12408,78,DMR,Daniel Muñoz,...,0,0,0,0,2,0,0.11304514110088348,0.8254843950271606,0.5870901346206665,5

# Team

In [6]:
dfs = scrapper.scrape_team("https://understat.com/team/Crystal_Palace/2018")

/home/victor/Documentos/Programação/Football/Scrapping/experiments/OwnScrapper/../../Understat/Understat.py:36: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 36 of the file /home/victor/Documentos/Programação/Football/Scrapping/experiments/OwnScrapper/../../Understat/Understat.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(res.content)

In [7]:
dfs[0].head()

,id,isResult,side,datetime,result,home_team_id,home_team_name,home_team_short_name,away_team_id,away_team_name,away_team_short_name,home_goals,away_goals,home_xG,away_xG,forecast_win,forecast_draw,forecast_loss
0,9201,True,a,2018-08-11 17:00:00,w,228,Fulham,FLH,78,Crystal Palace,CRY,0,2,0.638076,1.07816,0.215503,0.326358,0.458138
1,9216,True,h,2018-08-20 22:00:00,l,78,Crystal Palace,CRY,87,Liverpool,LIV,0,2,0.368608,2.82183,0.028936,0.096465,0.874598
2,9224,True,a,2018-08-26 15:30:00,l,90,Watford,WAT,78,Crystal Palace,CRY,2,1,1.14596,1.21905,0.342764,0.278801,0.378435
3,9230,True,h,2018-09-01 14:00:00,l,78,Crystal Palace,CRY,74,Southampton,SOU,0,2,2.35193,3.13612,0.288597,0.166023,0.545379
4,9240,True,a,2018-09-15 14:00:00,w,219,Huddersfield,HUD,78,Crystal Palace,CRY,0,1,0.87744,0.746631,0.362701,0.348968,0.288331

In [8]:
dfs[5].head()

        stat shots goals        xG shots_against goals_against xG_against
1-15    1-15    50     3  5.909056            69             2   6.990477
16-30  16-30    66     4  6.121339            81             6   9.390842
31-45  31-45    70    13  8.487111            95             5   7.979949
46-60  46-60    87     6  9.481391            92            13   7.106291
61-75  61-75   106    10  9.829456            74            13   9.928724

# Player

In [9]:
player_stats, player_positions_df, shots_df = scrapper.scrape_player("https://understat.com/player/532")

/home/victor/Documentos/Programação/Football/Scrapping/experiments/OwnScrapper/../../Understat/Understat.py:18: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 18 of the file /home/victor/Documentos/Programação/Football/Scrapping/experiments/OwnScrapper/../../Understat/Understat.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(res.content)

In [10]:
shots_df.head()

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,season,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction
0,14625,25,MissedShots,0.8919999694824219,0.4370000076293945,0.029088299721479416,Cheikhou Kouyaté,h,532,OpenPlay,2014,Head,4754,West Ham,Tottenham,0,1,2014-08-16 15:00:00,Stewart Downing,Aerial
1,14634,51,MissedShots,0.735999984741211,0.629000015258789,0.013856399804353714,Cheikhou Kouyaté,h,532,OpenPlay,2014,RightFoot,4754,West Ham,Tottenham,0,1,2014-08-16 15:00:00,None,None
2,14709,25,SavedShot,0.9519999694824218,0.4929999923706055,0.13338899612426758,Cheikhou Kouyaté,a,532,FromCorner,2014,Head,4761,Crystal Palace,West Ham,1,3,2014-08-23 15:00:00,Ricardo Vaz Te,Chipped
3,14725,89,SavedShot,0.7869999694824219,0.675,0.025339700281620026,Cheikhou Kouyaté,a,532,OpenPlay,2014,RightFoot,4761,Crystal Palace,West Ham,1,3,2014-08-23 15:00:00,Aaron Cresswell,Pass
4,15252,24,BlockedShot,0.7580000305175781,0.500999984741211,0.02752630040049553,Cheikhou Kouyaté,a,532,OpenPlay,2014,RightFoot,4728,Hull,West Ham,2,2,2014-09-15 20:00:00,Stewart Downing,Pass

In [11]:
player_positions_df.head()

,goals_min,goals_max,goals_avg,xG_min,xG_max,xG_avg,shots_min,shots_max,shots_avg,assists_min,...,xA_avg,key_passes_min,key_passes_max,key_passes_avg,xGChain_min,xGChain_max,xGChain_avg,xGBuildup_min,xGBuildup_max,xGBuildup_avg
AMC,0.0003,0.0062,0.0023,0.000660,0.004983,0.002192,0.0111,0.0425,0.0218,0.0003,...,0.001843,0.0090,0.0451,0.0186,0.002750,0.010071,0.004880,0.001072,0.006206,0.002221
DC,0.0000,0.0021,0.0005,0.000028,0.001892,0.000494,0.0006,0.0171,0.0050,0.0000,...,0.000207,0.0003,0.0089,0.0021,0.000434,0.006843,0.001888,0.000380,0.006696,0.001771
DMC,0.0000,0.0044,0.0006,0.000050,0.003600,0.000667,0.0016,0.0264,0.0103,0.0000,...,0.000639,0.0022,0.0281,0.0087,0.000955,0.008132,0.003192,0.000889,0.006581,0.002538
DR,0.0000,0.0017,0.0003,0.000006,0.001722,0.000337,0.0002,0.0149,0.0052,0.0000,...,0.000806,0.0029,0.0210,0.0082,0.001072,0.008822,0.002823,0.000681,0.007371,0.002188
MC,0.0000,0.0052,0.0009,0.000033,0.003700,0.000922,0.0012,0.0354,0.0124,0.0000,...,0.000968,0.0021,0.0377,0.0115,0.000854,0.012126,0.003672,0.000642,0.008059,0.002569

In [15]:
player_stats[2][3][0]

'2017'

In [16]:
player_stats[2][3][1]

,situation,season,goals,shots,xG,assists,key_passes,xA,npg,npxG,time
OpenPlay,OpenPlay,2017,1,13,1.3034664141014218,3,14,0.6528683071956038,1,1.3034664141014218,2803
FromCorner,FromCorner,2017,1,6,0.44615161046385765,0,1,0.14551499485969543,1,0.44615161046385765,2803
SetPiece,SetPiece,2017,0,3,0.04754351079463959,0,1,0.07818350195884705,0,0.04754351079463959,2803